# ==========================================
# TAYPRO USB SECURITY MONITOR
# ==========================================

$BasePath = "C:\ProgramData\Taypro\USBSecurity"

$ConfigFile     = "$BasePath\settings.json"
$CredentialFile = "$BasePath\smtp-secret.dat"
$LogFile        = "$BasePath\USBSecurity.log"

# ==========================================
# LOG FUNCTION
# ==========================================

function Write-Log {
    param(
        [string]$Message
    )

    $Time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

    Add-Content -Path $LogFile `
        -Value "[$Time] $Message"
}

# ==========================================
# LOAD CONFIGURATION
# ==========================================

if (!(Test-Path $ConfigFile)) {

    Write-Log "ERROR: settings.json not found."

    exit 1
}

try {

    $Config = Get-Content $ConfigFile -Raw |
        ConvertFrom-Json

}
catch {

    Write-Log "ERROR loading configuration: $($_.Exception.Message)"

    exit 1
}

$SmtpServer = $Config.SmtpServer
$SmtpPort   = [int]$Config.SmtpPort
$From       = $Config.From
$To         = $Config.To
$AuthUser   = $Config.AuthUser

# ==========================================
# LOAD ENCRYPTED SMTP PASSWORD
# ==========================================

if (!(Test-Path $CredentialFile)) {

    Write-Log "ERROR: SMTP credential not found."

    exit 1
}

try {

    $EncryptedPassword = Get-Content $CredentialFile -Raw

    $EncryptedBytes = [Convert]::FromBase64String(
        $EncryptedPassword
    )

    $PasswordBytes = [System.Security.Cryptography.ProtectedData]::Unprotect(
        $EncryptedBytes,
        $null,
        [System.Security.Cryptography.DataProtectionScope]::LocalMachine
    )

    $Password = [System.Text.Encoding]::UTF8.GetString(
        $PasswordBytes
    )

}
catch {

    Write-Log "ERROR decrypting SMTP password: $($_.Exception.Message)"

    exit 1
}

# ==========================================
# SEND EMAIL
# ==========================================

function Send-USBAlert {

    param(
        [string]$DriveLetter,
        [string]$VolumeName
    )

    $ComputerName = $env:COMPUTERNAME

    try {

        $UserName = (
            Get-CimInstance Win32_ComputerSystem
        ).UserName

    }
    catch {

        $UserName = "Unknown"
    }

    $Time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

    $Subject = "USB DEVICE DETECTED - $ComputerName"

    $Body = @"
USB SECURITY ALERT

A USB storage device has been connected.

Computer Name : $ComputerName
Logged-in User: $UserName
Drive Letter  : $DriveLetter
Volume Name   : $VolumeName
Time          : $Time

This is an automated alert generated by Taypro local security policy.
"@

    Write-Log "USB DETECTED | Computer=$ComputerName | User=$UserName | Drive=$DriveLetter | Volume=$VolumeName"

    $Smtp = $null
    $Message = $null

    try {

        $SecurePassword = ConvertTo-SecureString `
            $Password `
            -AsPlainText `
            -Force

        $Credential = New-Object `
            System.Management.Automation.PSCredential(
                $AuthUser,
                $SecurePassword
            )

        $Smtp = New-Object System.Net.Mail.SmtpClient(
            $SmtpServer,
            $SmtpPort
        )

        $Smtp.EnableSsl = $true
        $Smtp.Timeout = 15000
        $Smtp.UseDefaultCredentials = $false
        $Smtp.Credentials = $Credential.GetNetworkCredential()

        $Message = New-Object System.Net.Mail.MailMessage

        $Message.From = $From
        $Message.To.Add($To)
        $Message.Subject = $Subject
        $Message.Body = $Body

        $Smtp.Send($Message)

        Write-Log "EMAIL SENT SUCCESSFULLY."

    }
    catch {

        Write-Log "EMAIL FAILED: $($_.Exception.Message)"
    }
    finally {

        if ($Message) {
            $Message.Dispose()
        }

        if ($Smtp) {
            $Smtp.Dispose()
        }
    }
}

# ==========================================
# START MONITOR
# ==========================================

Write-Log "=========================================="
Write-Log "TAYPRO USB SECURITY MONITOR STARTED"
Write-Log "Computer: $env:COMPUTERNAME"
Write-Log "=========================================="

# ==========================================
# USB INSERTION EVENT
# ==========================================

$query = @"
SELECT * FROM Win32_VolumeChangeEvent
WHERE EventType = 2
"@

try {

    Register-WmiEvent `
        -Query $query `
        -SourceIdentifier "TayproUSBDetection" `
        -ErrorAction Stop

}
catch {

    Write-Log "ERROR registering USB event: $($_.Exception.Message)"

    exit 1
}

# ==========================================
# CONTINUOUS MONITORING
# ==========================================

while ($true) {

    try {

        $Event = Wait-Event `
            -SourceIdentifier "TayproUSBDetection"

        if ($Event) {

            try {

                $DriveLetter =
                    $Event.SourceEventArgs.NewEvent.DriveName

                Start-Sleep -Seconds 2

                if ($DriveLetter) {

                    $Volume = Get-CimInstance Win32_LogicalDisk `
                        -Filter "DeviceID='$DriveLetter'"

                    if ($Volume) {

                        $VolumeName = $Volume.VolumeName

                        Send-USBAlert `
                            -DriveLetter $DriveLetter `
                            -VolumeName $VolumeName
                    }
                }

            }
            catch {

                Write-Log "USB EVENT ERROR: $($_.Exception.Message)"
            }

            Remove-Event `
                -SourceIdentifier "TayproUSBDetection" `
                -ErrorAction SilentlyContinue
        }

    }
    catch {

        Write-Log "MONITOR ERROR: $($_.Exception.Message)"

        Start-Sleep -Seconds 5
    }
}